### ISSUE TITLE
Library path expansion in do_bsd_openat

### ISSUE THREAD

**Issue by markcorbinuk** [seanbruno/qemu-bsd-user#84]
Whilst working on adding RISC-V user mode support I noticed that it was not possible to run qemu-&lt;arch&gt;-static outside of a jail. I was expecting to be able to use BSD user mode in a similar fashion to Linux user mode such that the following would work:

qemu-&lt;arch&gt;-static -L &lt;path-to-arch-rootfs&gt; &lt;arch-executable&gt;

I tracked the problem down to the (lack of) path expansion in do_bsd_openat function in bsd-user/bsd-file.h The 'path' function has been used elsewhere to prepend the &lt;path-to-arch-rootfs&gt; to the file name, but in this case it has been commented out. If I replace the 'p' parameter with 'path(p)' I can run qemu-&lt;arch&gt;-static standalone as described above. I've tested this with arm, aarch64 and riscv64 (both standalone and in jails) and haven't encountered any issues. Without this change the program attempts to open shared libraries in, for example, /lib instead of &lt;path-to-arch-rootfs&gt;/lib

Linux user mode uses the 'path' function in it's call to openat (see the return value call in the do_openat function in linux-user/syscall.c).

I was wondering if there was any reason not to change 'p' to 'path(p)' in the do_bsd_openat function?

Thanks

**Comment by kevans91** [comment]
Hmm... sson@ effectively "broke" this in commit 14e7334e7b197b along with some iovec locking changes. It's not clear to me that this was actually related or intended, rather than perhaps some residual debugging effort that was accidentally committed. I can't see a reason we shouldn't revert that part and make do_bsd_openat otherwise match do_bsd_open just above it.

**Comment by markcorbinuk** [comment]
This has been resolved by pull request #85
